### ISSUE TITLE
Add support for device H7020

### ISSUE THREAD

**Issue by cjlucas** [Galorhallen/govee-local-api#10]
Could you add support for H7020? It's identical to the H7021, except it's half as long. As far as capabilities, they should be the same.

**Comment by Galorhallen** [comment]
Hi, thanks for the report!
I'll add it in the next release.

**Comment by Galorhallen** [comment]
Support added in https://github.com/Galorhallen/govee-local-api/commit/ee69e6dee2f3ec739ec459c9f0c58ad80575fcd2
