### ISSUE TITLE
Device not supported H61BE

### ISSUE THREAD

**Issue by aklausing** [Galorhallen/govee-local-api#16]
Hi,
indeed the device type is not supported due to the homeassistand website. But I know that it should do more than just "on and off". A friend of mine uses the same strip with iobroker and the govee local adapter for iobroker and it supports rgb, temperature and dimmer (and of course on and off).

Log only states 
2024-03-28 18:25:23.550 WARNING (MainThread) [homeassistant.components.govee_light_local.coordinator] Device H61BE is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'

Is there any plan to integrate new light strip models in the near future. I also have a H6172 running with the integration ad i love that has no need for cloud anymore.

**Comment by Galorhallen** [comment]
Hi @aklausing,
  thanks for letting me know about the H61BE, if it gets detected it can be managed by the integration. I'll add it to the next release.

Regarding the H6172, does it get detected by the integration? If so, it should be print a message similar to the one you posted.
If it doesn't get detected, can you please check in the configuration page for the device in the Govee app if if the local api is supported?

Thanks,
Galo

**Comment by Josuruma** [comment]
I got the H6172 too and it is fully detected and functional.
![image](https://github.com/Galorhallen/govee-local-api/assets/35657189/b453897d-6f22-45ae-ab6c-dc8906077614)

**Comment by Galorhallen** [comment]
Support for `H61BE` added in https://github.com/Galorhallen/govee-local-api/commit/1a2136f0e86f8a0a81fda471d76ddd05690230e0
