### ISSUE TITLE
Device H6092 is not supported.

### ISSUE THREAD

**Issue by hong9life** [Galorhallen/govee-local-api#18]
Hi, 

I got the following message from log info. 
Can you add this device? I am using Home Assistant 2024. 4.4.

```
로거: homeassistant.components.govee_light_local.config_flow
소스: runner.py:189
통합구성요소: Govee lights local (관련 문서, 문제)
처음 발생: 오후 5:17:53 (1 발생)
마지막 로그인: 오후 5:17:53

Device H6092 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'
```

**Comment by Galorhallen** [comment]
Hi @hong9life,
 I see that the device is not a led strip, but some kind of projector, is this correct?

Anyway if the integration detects it, it should be controllable by local api, but can you please verify if from the app you can actually make it project a whole color (rgb or temperature)?
I'm assuming brightness is controllable from the app, right?

Thanks,
Galo
