### ISSUE TITLE
Color support for H61D3 and H608B

### ISSUE THREAD

**Issue by matthewlehew** [Galorhallen/govee-local-api#21]
Thanks for maintaining this repo. I have H61D3 (Govee Neon Rope Light 2) and H608B (Govee RGBIC String Downlights). Both have LAN control enabled in the Govee app, and both appear in Home Assistant but only with on/off capabilities.

Is it possible to add them so the color can be controlled within Home Assistant?

**Comment by Galorhallen** [comment]
Thanks @matthewlehew!

**Comment by matthewlehew** [comment]
Hey @Galorhallen, just for awareness, is there a ballpark cadence for when this change would eventually filter to the local govee Home Assistant integration?
