### ISSUE TITLE
Device H70C2 not supported

### ISSUE THREAD

**Issue by schariwari** [Galorhallen/govee-local-api#24]
Hi, 

Got the error message 
`Logger: homeassistant.components.govee_light_local.coordinator
Quelle: runner.py:190
Integration: Govee lights local (Dokumentation, Probleme)
Erstmals aufgetreten: 12:51:11 (1 Vorkommnisse)
Zuletzt protokolliert: 12:51:11

Device H70C2 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'`

This ist the so called "Christmas light strip" (which I also use during the whole year ;-)

Can control the strip via the app locally, so the API should be available.

TIA

**Comment by Galorhallen** [comment]
Done in 0fb4f4b757c87e1222d0f498fe627a6a19c2a54d

**Comment by schariwari** [comment]
Thank you so much ;-)
