### ISSUE TITLE
Device H61E0 is not supported

### ISSUE THREAD

**Issue by brodock** [Galorhallen/govee-local-api#30]
homeassistant  | 2024-06-15 16:11:55.916 WARNING (MainThread) [homeassistant.components.govee_light_local.coordinator] Device H61E0 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'

**Comment by Galorhallen** [comment]
Added in https://github.com/Galorhallen/govee-local-api/pull/36
