### ISSUE TITLE
Add support for H6099

### ISSUE THREAD

**Issue by kino90** [Galorhallen/govee-local-api#40]
H6099 is not supported yet, would you please add it? 

I'd love at least to be able to turn it on/off together with my TV 👍🏼

Thanks

**Comment by Galorhallen** [comment]
Hi,
  is the device detected by the integration? Does it support local api?

**Comment by kino90** [comment]
How can I check that?

**Comment by Galorhallen** [comment]
You can enable the API following this guide https://app-h5.govee.com/user-manual/wlan-guide

**Comment by kino90** [comment]
Guess is not compatible then 😭 
![Screenshot_2024-07-21-15-05-19-63_609483d6a3d5c87c635c14d24d761e16](https://github.com/user-attachments/assets/c9ea4070-6d88-457a-bce6-5e2f0dc9047b)
