### ISSUE TITLE
H7038

### ISSUE THREAD

**Issue by smoukaruna** [Galorhallen/govee-local-api#47]
Hello! Would it be possible to add support for H7038? Lan option is available!

Thank you :)

**Comment by Galorhallen** [comment]
Hi, can you confirm that the device supports rgb, brightness and temperature controls? Thanks

**Comment by smoukaruna** [comment]
Hello, yes it does! 
Here are some Screenshots from the govee App 

Greetings
![Screenshot_20240822_131106_Govee Home](https://github.com/user-attachments/assets/1d3fb0aa-e3e5-494c-869f-73bbdad50e8d)
![Screenshot_20240822_131032_Govee Home](https://github.com/user-attachments/assets/78aded77-37c5-42d4-8c91-c2b181ce3d56)

**Comment by Galorhallen** [comment]
Added in 1.5.2
