### ISSUE TITLE
H705E Only showing ON / OFF 

### ISSUE THREAD

**Issue by andyblac** [Galorhallen/govee-local-api#55]
can you add support for colour and brightness.

Thanks
Andrew

**Comment by andyblac** [comment]
created a PR https://github.com/Galorhallen/govee-local-api/pull/56

**Comment by Galorhallen** [comment]
Merged
Thanks!

**Comment by andyblac** [comment]
any idea when will this reach Home Assistant ?

**Comment by Timple** [comment]
It already did. My lights work on the latest home assistant version.

**Comment by andyblac** [comment]
> It already did. My lights work on the latest home assistant version.

you sure you get Brightness and color etc, what version of HA ??, it not in the master git only DEV branch local API,

**Comment by Timple** [comment]
I'm running `2024.9.2`

**Comment by andyblac** [comment]
> I'm running `2024.9.2`

well not sure how, as HA only has version `1.5.2` for govee_local_api, and it is not included in that version

https://github.com/home-assistant/core/blob/dev/homeassistant/components/govee_light_local/manifest.json

**Comment by Timple** [comment]
My apologies!

I was mixing your PR up with mine: https://github.com/Galorhallen/govee-local-api/pull/54

Yours doesn't seem to be released yet :slightly_frowning_face:

**Comment by andyblac** [comment]
> My apologies!
> 
> I was mixing your PR up with mine: #54
> 
> Yours doesn't seem to be released yet 🙁

np, thanks for clarifying 😄

**Comment by Galorhallen** [comment]
> any idea when will this reach Home Assistant ?

Hi, sorry for the delay. Your PR was merges after the release of 1.5.2. I'll try to make a new release asap

**Comment by andyblac** [comment]
> > any idea when will this reach Home Assistant ?
> 
> Hi, sorry for the delay. Your PR was merges after the release of 1.5.2. I'll try to make a new release asap

sorry for keep asking, but is there any chance you can get this merged into master branch, so it become available to HA core.
Thanks
Andrew
