### ISSUE TITLE
Support for H706B missing

### ISSUE THREAD

**Issue by DonDizzurp** [Galorhallen/govee-local-api#63]
Full RGB and effects support missing for the H706B. These are the 150ft Permanent Outdoor Lights Pro.

H706A (100ft) and H706C (200ft) might also be missing but I cannot confirm.

**Comment by Stupefy** [comment]
I also have this warning message that tells me to create an issue here.  At-least we can turn them on and off..  If Home Assistant could support me setting the color of each individual light that would be amazing!

**Comment by Galorhallen** [comment]
Support will be in the next release
