### ISSUE TITLE
[New Device] H608A

### ISSUE THREAD

**Issue by niklasfink** [Galorhallen/govee-local-api#7]
Hey, it would be great if you could add the device H608A

> WARNING (MainThread) [homeassistant.components.govee_light_local.coordinator] Device H608A is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'

It's the Govee String Downlights: https://eu.govee.com/products/govee-rgbic-string-downlights

They can do pretty much everything, including control of single light spots, music and so on.

**Comment by Galorhallen** [comment]
Hi,
 thanks for the report. The model will be added in the next release.

> They can do pretty much everything, including control of single light spots, music and so on.

Unfortunately local api doesn't support single light control, music or scenes. They allow to control the strip as a whole.
