### ISSUE TITLE
Support for Govee H600D

### ISSUE THREAD

**Issue by twantythree** [Galorhallen/govee-local-api#70]
Hi Galorhallen,

I‘m writing to kindly inquire if it would be possible to integrate support for the Govee GU10 smart lamp, model number H600D, into Home Assistant. This device offers great features and would be a valuable addition for users managing their smart home systems.

If any further details or information about the device are required, I would be happy to assist. Thank you for considering this request, and for all the amazing work you do to enhance the Home Assistant platform.

Looking forward to your response.

**Comment by Paulomart** [comment]
Im confused what happend here. According to Govee Local API is not available for H600D: https://app-h5.govee.com/user-manual/wlan-guide

I think it should not be supported in by this library then?
